// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmuizdwvqkkqgjsnjxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdWl6ZHd2cWtrcWdqc25qeHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDA4OTEsImV4cCI6MjA2NDUxNjg5MX0.rAga6kUtG-QRkKr1TzZDRwUwGetNTN7I8JNULRAGjpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);